Rewrote namespace-markup as a Perl script.

diff --git a/bin/namespace-markup b/bin/namespace-markup
--- a/bin/namespace-markup
+++ b/bin/namespace-markup
@@ -1,21 +1,24 @@
 #!/bin/bash
-# mymarkup
+# namespace-markup
 
-# function usage ()
-# {
-#     echo "usage: mymarkup [-p prefix] file ..." >&2;
-#     exit 2;
-# }
+function usage ()
+{
+    echo "usage: namespace-markup [-k filename -v namespace] [-k ... -v ...] file ..." >&2;
+    exit 2;
+}
 
-# prefix=''
-# while getopts hp: opt; do
-# 	case $opt in
-#       h) usage;;
-# 	    p) prefix=$OPTARG;;
-# 	    *) echo "error: invalid option given." >&2; usage;;
-# 	esac
-# done
-# shift $[ OPTIND - 1 ]
+namespaces='%namespaces = ('
+while getopts hk:v: opt; do
+	case $opt in
+      h) usage;;
+	    k) namespaces="$namespaces '$OPTARG',";;
+	    v) namespaces="$namespaces '$OPTARG',";;
+	    *) echo "error: invalid option given." >&2; usage;;
+	esac
+done
+shift $[ OPTIND - 1 ]
+
+namespaces="$namespaces ); ";
 
 # Let's add a prefix based on the filename.
-/opt/local/libexec/noweb/markup "$@" | perl -pe 'if (/^\@file ([^\.:]+)[^:]*$/) { $file = $1; }; s/^\@(defn|use) ([^+][^:]*)$/\@\1 $file:\2/'
+/opt/local/libexec/noweb/markup "$@" | perl -pe "$namespaces"'if (/^\@file ([^\.:]+)[^:]*$/) { $file = $1; if (!(defined $namespaces{$file})) { $namespaces{$file} = $file; print STDERR "setting it to $file $namespaces{$file} ";} print STDERR %namespaces; } s/^\@(defn|use) ([^+][^:]*)$/\@\1 $namespaces{$file}:\2/;'
