Switched to unified-procedures for better scheme integration, and it's now working.

diff --git a/bin/runtests.in b/bin/runtests.in
--- a/bin/runtests.in
+++ b/bin/runtests.in
@@ -1,9 +1,17 @@
 #!/bin/bash 
 # runtests
 
-if [ $# -eq 0 ]; then
+usage() {
    echo "usage: runtests <X.test.scm ...>" >&2;
-   exit 2;
-fi
+}
 
-DYLD_LIBRARY_PATH=@abs_top_srcdir@/src @GUILE@ -L @abs_top_builddir@/src -L @abs_top_srcdir@/support/scheme -L @abs_top_srcdir@/.. -L @abs_top_srcdir@/../noweb-emacsy "$@"
+prefix=""
+while getopts d opt; do
+	case $opt in
+	    d) prefix="gdb --args";;
+	    *) echo "error: invalid option given." >&2; usage;;
+	esac
+done
+shift $[ OPTIND - 1 ]
+
+DYLD_LIBRARY_PATH=@abs_top_srcdir@/src:@abs_top_builddir@/src/minimal-cognition/.libs: $prefix @GUILE@ -L @abs_top_builddir@/src -L @abs_top_srcdir@/support/scheme -L @abs_top_srcdir@/.. -L @abs_top_srcdir@/../emacsy/src -l @abs_top_srcdir@/../emacsy/src/line-pragma.scm "$@"
